### Source and Build ###
FROM node:latest AS ng-builder
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install --force
COPY . /app
RUN $(npm bin)/ng build --prod

### NGINX app deploy ###
FROM nginx
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY --from=ng-builder /app/dist/gol-voucher-ui /usr/share/nginx/html

### Environment variables ###
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
